In [ ]:
import pandas as pd
import numpy as np
import sklearn
import warnings
warnings.filterwarnings("ignore")

In [ ]:
data = pd.read_csv("ThoraricSurgery.csv")
data.head(2)

,id,diagnose,in_vol,out_vol,pain,Haemoptysis,short_breath,cough,weekness,tumour_size,diabetes,breathing_difficulty,other_disease,smoking,asthma,age,survive
0,1,DGN2,2.88,2.16,F,F,F,T,T,OC14,F,F,F,T,F,60,2
1,2,DGN3,3.40,1.88,F,F,F,F,F,OC12,F,F,F,T,F,51,2

In [ ]:
data.columns

Index(['id', 'diagnose', 'in_vol', 'out_vol', 'pain', 'Haemoptysis',
       'short_breath', 'cough', 'weekness', 'tumour_size', 'diabetes',
       'breathing_difficulty', 'other_disease', 'smoking', 'asthma', 'age',
       'survive'],
      dtype='object')

In [ ]:
data.isnull().sum()

id                      0
diagnose                0
in_vol                  0
out_vol                 0
pain                    0
Haemoptysis             0
short_breath            0
cough                   0
weekness                0
tumour_size             0
diabetes                0
breathing_difficulty    0
other_disease           0
smoking                 0
asthma                  0
age                     0
survive                 0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470 entries, 0 to 469
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    470 non-null    int64
 1   diagnose              470 non-null    object
 2   in_vol                470 non-null    float64
 3   out_vol               470 non-null    float64
 4   pain                  470 non-null    object
 5   Haemoptysis           470 non-null    object
 6   short_breath          470 non-null    object
 7   cough                 470 non-null    object
 8   weekness              470 non-null    object
 9   tumour_size           470 non-null    object
 10  diabetes              470 non-null    object
 11  breathing_difficulty  470 non-null    object
 12  other_disease         470 non-null    object
 13  smoking               470 non-null    object
 14  asthma                470 non-null    object
 15  age                   470 non-null    int64
 16  survive               470 non-null    int64
dtypes: float64(2), int64(3), object(12)
memory usage: 62.5+ KB

In [ ]:
#To create dummies (categories)
diagnose = pd.get_dummies(data["diagnose"],drop_first=True)
diagnose.head(2)

   DGN2  DGN3  DGN4  DGN5  DGN6  DGN8
0     1     0     0     0     0     0
1     0     1     0     0     0     0

In [ ]:
pain = pd.get_dummies(data["pain"],drop_first=True)
pain.head(2)

   T
0  0
1  0

In [ ]:
Haemoptysis = pd.get_dummies(data["Haemoptysis"],drop_first=True)
Haemoptysis.head(2)

   T
0  0
1  0

In [ ]:
short_breath  = pd.get_dummies(data["short_breath"],drop_first=True)
short_breath .head(2)

   T
0  0
1  0

In [ ]:
cough = pd.get_dummies(data["cough"],drop_first=True)
cough.head(2)

   T
0  1
1  0

In [ ]:
weekness = pd.get_dummies(data["weekness"],drop_first=True)
weekness.head(2)

   T
0  1
1  0

In [ ]:
tumour_size = pd.get_dummies(data["tumour_size"],drop_first=True)
tumour_size.head(2)

   OC12  OC13  OC14
0     0     0     1
1     1     0     0

In [ ]:
diabetes = pd.get_dummies(data["diabetes"],drop_first=True)
diabetes.head(2)

   T
0  0
1  0

In [ ]:
breathing_difficulty = pd.get_dummies(data["breathing_difficulty"],drop_first=True)
breathing_difficulty.head(2)

   T
0  0
1  0

In [ ]:
other_disease = pd.get_dummies(data["other_disease"],drop_first=True)
other_disease.head(2)

   T
0  0
1  0

In [ ]:
smoking = pd.get_dummies(data["smoking"],drop_first=True)
smoking.head(2)

   T
0  1
1  1

In [ ]:
asthma = pd.get_dummies(data["asthma"],drop_first=True)
asthma.head(2)

   T
0  0
1  0

In [ ]:
data = pd.concat([data,diagnose, pain,	Haemoptysis,	short_breath,	cough,	weekness,	tumour_size,	diabetes,	breathing_difficulty,	other_disease,	smoking,	asthma],axis = 1)
data.head(2)

,id,diagnose,in_vol,out_vol,pain,Haemoptysis,short_breath,cough,weekness,tumour_size,...,T,T,OC12,OC13,OC14,T,T,T,T,T
0,1,DGN2,2.88,2.16,F,F,F,T,T,OC14,...,1,1,0,0,1,0,0,0,1,0
1,2,DGN3,3.40,1.88,F,F,F,F,F,OC12,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
data.drop(['id', 'diagnose', 'pain',	'Haemoptysis',	'short_breath',	'cough',	'weekness',	'tumour_size',	'diabetes',	'breathing_difficulty',	'other_disease',	'smoking',	'asthma'],axis=1,
                  inplace=True)
data.head()

,in_vol,out_vol,age,survive,DGN2,DGN3,DGN4,DGN5,DGN6,DGN8,...,T,T,OC12,OC13,OC14,T,T,T,T,T
0,2.88,2.16,60,2,1,0,0,0,0,0,...,1,1,0,0,1,0,0,0,1,0
1,3.40,1.88,51,2,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
2,2.76,2.08,59,2,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
3,3.68,3.04,54,2,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2.44,0.96,73,1,0,1,0,0,0,0,...,1,1,0,0,0,0,0,0,1,0

In [ ]:
#Training and Testing data
X =  data.drop("survive",axis=1)
y =  data["survive"]
from sklearn.model_selection import train_test_split

In [ ]:
#Splitting into training set and testing set
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

LogisticRegression()

In [ ]:
predictions = logmodel.predict(X_test)

In [ ]:
#Metrics
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,predictions)*100)

84.04255319148936

In [ ]:
X_train.columns

Index(['in_vol', 'out_vol', 'age', 'DGN2', 'DGN3', 'DGN4', 'DGN5', 'DGN6',
       'DGN8', 'T', 'T', 'T', 'T', 'T', 'OC12', 'OC13', 'OC14', 'T', 'T', 'T',
       'T', 'T'],
      dtype='object')

In [ ]:
predictions = logmodel.predict([[22,11,39,1,0,0,0,0,0,1,1,1,1,1,1,0,0,1,1,1,1,1]])
predictions

array([2])

In [ ]:
!pip install flask-ngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting flask-ngrok
  Downloading flask_ngrok-0.0.25-py3-none-any.whl (3.1 kB)
Requirement already satisfied: Flask>=0.8 in /usr/local/lib/python3.7/dist-packages (from flask-ngrok) (1.1.4)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from flask-ngrok) (2.23.0)
Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (7.1.2)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (2.11.3)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (1.1.0)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (1.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2<3.0,>=2.10.1->Flask>=0.8->flask-ngrok) (2.0.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (2022.9.24)
Installing collected packages: flask-ngrok
Successfully installed flask-ngrok-0.0.25

In [ ]:
!pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyngrok
  Downloading pyngrok-5.1.0.tar.gz (745 kB)
     |████████████████████████████████| 745 kB 30.8 MB/s
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/dist-packages (from pyngrok) (6.0)
Building wheels for collected packages: pyngrok
  Building wheel for pyngrok (setup.py) ... done
  Created wheel for pyngrok: filename=pyngrok-5.1.0-py3-none-any.whl size=19006 sha256=ef453f31c583e36be3080f8f3ef3cdeeb60803646a4115d393c9485dd06e1be9
  Stored in directory: /root/.cache/pip/wheels/bf/e6/af/ccf6598ecefecd44104069371795cb9b3afbcd16987f6ccfb3
Successfully built pyngrok
Installing collected packages: pyngrok
Successfully installed pyngrok-5.1.0

In [ ]:
from flask import Flask
from pyngrok import ngrok

In [ ]:
from flask_ngrok import run_with_ngrok
from flask import Flask,jsonify
app =Flask(__name__)
ngrok.set_auth_token("2HzSiYgPX8xag1kh3su25h4ah4p_2XebadhVb5KSvQEixAGKt")
run_with_ngrok(app) #starts ngrok when the app is running
@app.route("/<float:in_vol>/<float:out_vol>/<int:age>/<diagnose>/<pain>/<Haemoptysis>/<short_breath>/<cough>/<weekness>/<tumour_size>/<diabetes>/<breathing_difficulty>/<other_disease>/<smoking>/<asthma>")
def home(in_vol,	out_vol ,	age, diagnose,		pain,	Haemoptysis,	short_breath,	cough,	weekness,	tumour_size,	diabetes,	breathing_difficulty,	other_disease,	smoking,	asthma):
  p = []
  p += [in_vol,	out_vol, 	age]
  #'DGN2', 'DGN3', 'DGN4', 'DGN5', 'DGN6','DGN8'
  if diagnose.casefold() == "DGN2":
    p+=[1,0,0,0,0,0]
  elif diagnose.casefold() == "DGN3":
    p+=[0,1,0,0,0,0]
  elif diagnose.casefold() == "DGN4":
    p+=[0,0,1,0,0,0]
  elif diagnose.casefold() == "DGN5":
    p+=[0,0,0,1,0,0]
  elif diagnose.casefold() == "DGN6":
    p+=[0,0,0,0,1,0]
  elif diagnose.casefold() == "DGN8":
    p+=[0,0,0,0,0,1]
  else:
    p+=[0,0,0,0,0,0]
  if pain.casefold() == "True":
    p+=[1]
  else:
    p+=[0]
  if Haemoptysis.casefold() == "True":
    p+=[1]
  else:
    p+=[0]
  if short_breath.casefold() == "True":
    p+=[1]
  else:
    p+=[0]
  if cough.casefold() == "True":
    p+=[1]
  else:
    p+=[0]
  if weekness.casefold() == "True":
    p+=[1]
  else:
    p+=[0]
  if tumour_size.casefold() == "OC12":
    p+=[1,0,0]
  elif tumour_size.casefold() == "OC13":
    p+=[0,1,0]
  elif tumour_size.casefold() == "OC14":
    p+=[0,0,1]
  else:
    p+=[0,0,0]
  if diabetes.casefold() == "True":
    p+=[1]
  else:
    p+=[0]
  if breathing_difficulty.casefold() == "True":
    p+=[1]
  else:
    p+=[0]
  if other_disease.casefold() == "True":
    p+=[1]
  else:
    p+=[0]
  #other_disease,	smoking,	asthma,	age
  if smoking.casefold() == "True":
    p+=[1]
  else:
    p+=[0]
  if asthma.casefold() == "True":
    p+=[1]
  else:
    p+=[0]
  arr = np.array([p])
  predict =logmodel.predict(arr)
  if predict == [1]:
    result = {'result':'NotSurvived'}
  else:
    result = {'result':'Survived'}
  
  return jsonify(result)
app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

 * Running on http://2b0c-34-87-92-90.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040

INFO:werkzeug:127.0.0.1 - - [25/Nov/2022 04:23:12] "GET /12.3/4.5/48/DGN2/True%20/False%20/False%20/True%20/True%20/OC11/False%20/False%20/False%20/False%20/False HTTP/1.1" 200 -